### PR TITLE
pronounce

### PR DESCRIPTION
**Pull request by tkukec**
everyone can get pronouns they just have to add the ::after thingy

### CODE REVIEW

**Comment by tkukec** [comment]
wait theres a stray edit ill fix this brb

**Comment by tkukec** [comment]
should be good now

**Comment by TodePond** [comment]
hmm it doesnt seem to work for me. are you able to run it locally?

**Comment by tkukec** [comment]
it works for me. im on firefox so that might be the problem. ill test on chrome brb

**Comment by tkukec** [comment]
ok got it. firefox does the gradient for the whole thing including ::after, but chrome has them separate

**Comment by tkukec** [comment]
@TodePond should work on both not-firefox and firefox now. (idk how safari does it and i cant test it)

**Review by TodePond — COMMENTED** [review]
I will merge this if:

- animation is slowed down a lot, eg: `30s` or `40s`. its very distracting from other users currently.
- the pronouns are removed from mentions. its very long inline.
eg: 
```css
.at-PodeTond.💚::after {
  content: "";
  animation: none;
}
```

**Comment by tkukec** [comment]
seems like there are some conflicts so ill just make a new pr with those changes

**Pull request closed without merging**
