### PR TITLE
add gifs

### PR DESCRIPTION
**Pull request by evoL**
this adds gifs both as files to this repo and as support for posting gifs in /lab/login

## backend changes are necessary

relevant vals:

- https://www.val.town/v/evol/labLogin — removed `CREATE TABLE`, moved to a separate schema management script ran manually: https://www.val.town/v/evol/labLoginSchema
- https://www.val.town/v/evol/labLoginUpdateStatus — changed SQL query to include gif
- https://www.val.town/v/evol/labLoginGetUsers — changed SQL query to include gif

## demo

https://github.com/user-attachments/assets/1c913149-28ad-41fe-8f05-1ea54905e358

### CODE REVIEW

**Comment by TodePond** [comment]
holy shit

**Comment by TodePond** [comment]
i really want to do this before bluesky. will try to merge this weekend

**Comment by evoL** [comment]
um, hi

please add gifs...?

**Comment by evoL** [comment]
hi i'm helping out with the code review 

this is very good code and it definitely adds more than one gif, I'd give it a 7 out of 5

easy lgtm from me

**Pull request merged**
