### PR TITLE
Manual feed refresh button

### PR DESCRIPTION
**Pull request by RosyArts**

### CODE REVIEW

**Comment by TodePond** [comment]
nice. will test and merge tomorrow hopefully

**Comment by RosyArts** [comment]
thanks. I haven't actually tested this myself, it just calls `pullUserStatuses()`

**Comment by RosyArts** [comment]
tested now, seems to work

**Comment by RosyArts** [comment]
only concern is refresh spamming, i can add button cooldown if you want

**Comment by TodePond** [comment]
oh hey yeah a cooldown would be great. i know its easy to get around it, but it would do something to stop some people spamming it :)

**Comment by RosyArts** [comment]
Okay, cooldown added! Sorry If the code's a bit iffy. first time using js / typescript / whatever this is. As such feedback would be appreciated if you have the time

**Comment by RosyArts** [comment]
uhhh i didnt mean to delete those commits is there any way to get them back

**Pull request closed without merging**
